angular.module('gurpscc').constant 'disadvantages', {
  bad_sight:
    name:"bad_sight"
    label:"Bad Sight"
    type:"select"
    base_value:"Average"
    values:
      none:
        label:"Average"
        points_value:0
      bad_sight:
        label:"Bad Sight"
        points_value:-10
      very_bad_sight:
        label:"Very Bad Sight"
        points_value:-25
  bad_temper:
    name:"bad_temper"
    label:"Bad Temper"
    type:"toggle"
    points_value:-10
  bloodlust:
    name:"bloodlust"
    label:"Bloodlust"
    type:"toggle"
    points_value:-10
  code_of_honor:
    name:"code_of_honor"
    label:"Code of Honor"
    type:"select"
    base_value:"None"
    values:
      none:
       points_value:0
       label:"None"
      minor:
        points_value:-5
        label:"Minor"
      moderate:
        points_value:-10
        label:"Moderate"
      major:
        points_value:-10
        label:"Major"
  curious:
    name:"curious"
    label:"Curious"
    type:"toggle"
    points_value:-5
  delusion:
    name:"delusion"
    label:"Delusion"
    type:"select"
    base_value:"None"
    values:
      none:
        points_value:0
        label:"None"
      minor:
        points_value:-5
        label:"Minor"
      major:
        points_value:-10
        label:"Major"
      severe:
        points_value:-10
        label:"Severe"
  gluttony:
    name:"gluttony"
    label:"Gluttony"
    type:"toggle"
    points_value:-5
  greed:
    name:"greed"
    label:"Greed"
    type:"toggle"
    points_value:-15
  hard_of_hearing:
    name:"hard_of_hearing"
    label:"Hard of Hearing"
    type:"toggle"
    points_value:-10
  honesty:
    name:"honesty"
    label:"Honesty"
    type:"toggle"
    points_value:-10
  impulsiveness:
    name:"impulsiveness"
    label:"Impulsiveness"
    type:"toggle"
    points_value:-10
  intolerance:
    name:'intolerance'
    label:"Intolerance"
    type:"select"
    base_value:"None"
    values:
      none:
        points_value:0
        label:"None"
      thorough:
        label:"Thorough"
        points_value:-10
      specific_minor:
        label:"Specific, Minor"
        points_value:-1
      specific_moderate:
        label:"Specific, Moderate"
        points_value:-2
      specific_major:
        label:"Specific Major"
        points_value:-5

  jealousy:
    name:"jealousy"
    label:"Jealousy"
    type:"toggle"
    points_value:-1
  lecherousness:
    name:"lecherousness"
    label:"Lecherousness"
    type:"toggle"
    points_value:-15
  obsession:
    name:"obesssion"
    label:"Obsession"
    type:"select"
    base_value:"None"
    values:
      none:
        points_value:0
        label:"None"
      short_term:
        label:"Short-term"
        points_value:-5
      long_term:
        label:"Long-term"
        points_value:-10
  overconfidence:
    name:"overconfidence"
    label:"Overconfidence"
    type:"toggle"
    points_value:-5
  pacifism:
    name:"pacifism"
    label:"Pacifism"
    type:"select"
    base_value:"None"
    values:
      none:
        points_value:0
        label:"None"
      reluctant_killer:
        label:"Reluctant killer"
        points_value:-5
      cannot_harm_innocents:
        label:"Cannot harm innocents"
        points_value:-10
  phobia:
    name:"phobia"
    label:"Phobia"
    type:"select"
    base_value:"None"
    values:
      none:
        points_value:0
        label:"None"
      mild:
        label:"Mild"
        points_value:-5
      moderate:
        label:"Moderate"
        points_value:-10
      major:
        label:"Major"
        points_value:-15
  sense_of_duty:
    name:"sense_of_duty"
    label:"Sense of Duty"
    type:"select"
    base_value:"None"
    values:
      none:
        points_value:0
        label:"None"
      individual:
        label:"Individual"
        points_value:-2
      small_group:
        label:"Small group"
        points_value:-5
      large_group:
        label:"Large group"
        points_value:-10
      entire_race:
        label:"Entire race"
        points_value:-15
      every_living_being:
        label:"Every living being"
        points_value:-20
  truthfulness:
    name:"truthfulness"
    label:"Truthfulness"
    type:"toggle"
    points_value:-5
  unluckiness:
    name:"unluckiness"
    label:"Unluckiness"
    type:"toggle"
    points_value:-10
  vow:
    name:"vow"
    label:"Vow"
    type:"select"
    base_value:"None"
    values:
      none:
        points_value:0
        label:"None"
      minor:
        label:"Minor"
        points_value:-5
      major:
        label:"Major"
        points_value:-10
      great:
        label:"Great"
        points_value:-15
}
